### ISSUE TITLE
1.5.1: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [OSGeo/libgeotiff#34] opened 2020-02-28 08:15 UTC
```
+ /usr/bin/make -O -j48 V=1 VERBOSE=1 check
Making check in libxtiff
make[1]: Nothing to be done for 'check'.
Making check in .
Making check in bin
make[1]: Nothing to be done for 'check'.
Making check in man
Making check in man1
make[2]: Nothing to be done for 'check'.
make[2]: Nothing to be done for 'check-am'.
Making check in cmake
make[1]: Nothing to be done for 'check'.
Making check in test
/usr/bin/make  check-local
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/libgeotiff-1.5.1/test'
../test/testlistgeo ../bin/listgeo
============================================
Running ../test/testlistgeo using ../bin/listgeo:
============================================
proj_create: unrecognized format / unknown name
proj_create: unrecognized format / unknown name
proj_create: unrecognized format / unknown name
proj_create: unrecognized format / unknown name
proj_create: unrecognized format / unknown name
proj_create: unrecognized format / unknown name
proj_create: unrecognized format / unknown name
proj_create: unrecognized format / unknown name
proj_create: unrecognized format / unknown name
proj_create: unrecognized format / unknown name
diff testlistgeo_out with testlistgeo_out.dist
--- testlistgeo_out     2020-02-28 08:15:20.916206096 +0000
+++ ../test/testlistgeo_out.dist        2019-03-25 15:31:36.000000000 +0000
@@ -1697,11 +1697,11 @@
    Keyed_Information:
       GTModelTypeGeoKey (Short,1): ModelTypeProjected
       GTRasterTypeGeoKey (Short,1): RasterPixelIsArea
-      ProjectedCSTypeGeoKey (Short,1): Code-3035 (ETRS89-extended / LAEA Europe)
+      ProjectedCSTypeGeoKey (Short,1): Code-3035 (ETRS89 / LAEA Europe)
       End_Of_Keys.
    End_Of_Geotiff.

-PCS = 3035 (ETRS89-extended / LAEA Europe)
+PCS = 3035 (ETRS89 / LAEA Europe)
 Projection = 19986 (Europe Equal Area 2001)
 Projection Method: CT_LambertAzimEqualArea
    ProjCenterLatGeoKey: 52.000000 ( 52d 0' 0.00"N)

PROBLEMS HAVE OCCURRED
test file testlistgeo_out saved
```

**Comment by rouault** [comment] 2020-02-28 11:20
duplicate of https://github.com/OSGeo/libgeotiff/issues/22

**Closed by rouault** 2020-02-28 11:20 UTC
