### ISSUE TITLE
1.6.0: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [OSGeo/libgeotiff#55] opened 2021-03-26 20:19 UTC
```
+ cd libgeotiff-1.6.0
+ /usr/bin/make -O -j48 V=1 VERBOSE=1 check
Making check in libxtiff
make[1]: Nothing to be done for 'check'.
Making check in .
Making check in bin
make[1]: Nothing to be done for 'check'.
Making check in man
Making check in man1
make[2]: Nothing to be done for 'check'.
make[2]: Nothing to be done for 'check-am'.
Making check in cmake
make[1]: Nothing to be done for 'check'.
Making check in test
/usr/bin/make  check-local
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/libgeotiff-1.6.0/test'
../test/testlistgeo ../bin/listgeo
============================================
Running ../test/testlistgeo using ../bin/listgeo:
============================================
proj_create: unrecognized format / unknown name
proj_create: unrecognized format / unknown name
proj_create: unrecognized format / unknown name
proj_create: unrecognized format / unknown name
proj_create: unrecognized format / unknown name
proj_create: unrecognized format / unknown name
proj_create: unrecognized format / unknown name
proj_create: unrecognized format / unknown name
proj_create: unrecognized format / unknown name
proj_create: unrecognized format / unknown name
diff testlistgeo_out with testlistgeo_out.dist
--- testlistgeo_out     2021-03-26 20:16:43.122509207 +0000
+++ testlistgeo_out.dist.tmp    2021-03-26 20:16:43.117509197 +0000
@@ -1566,6 +1566,9 @@
    ProjFalseEastingGeoKey: 649328.000000 m
    ProjFalseNorthingGeoKey: 665262.000000 m
 GCS: 4258/ETRS89
+Datum: 6258/European Terrestrial Reference System 1989
+Ellipsoid: 7019/GRS 1980 (6378137.00,6356752.31)
+Prime Meridian: 8901/Greenwich (0.000000/  0d 0' 0.00"E)
 Projection Linear Units: 9001/metre (1.000000m)

 Corner Coordinates:
@@ -1616,6 +1619,9 @@
    ProjFalseEastingGeoKey: 649328.000000 m
    ProjFalseNorthingGeoKey: 665262.000000 m
 GCS: 4258/ETRS89
+Datum: 6258/European Terrestrial Reference System 1989
+Ellipsoid: 7019/GRS 1980 (6378137.00,6356752.31)
+Prime Meridian: 8901/Greenwich (0.000000/  0d 0' 0.00"E)
 Projection Linear Units: 9001/metre (1.000000m)

 Corner Coordinates:
@@ -1744,6 +1750,9 @@
    ProjFalseEastingGeoKey: 4321000.000000 m
    ProjFalseNorthingGeoKey: 3210000.000000 m
 GCS: 4258/ETRS89
+Datum: 6258/European Terrestrial Reference System 1989
+Ellipsoid: 7019/GRS 1980 (6378137.00,6356752.31)
+Prime Meridian: 8901/Greenwich (0.000000/  0d 0' 0.00"E)
 Projection Linear Units: 9001/metre (1.000000m)

 Corner Coordinates:
@@ -1790,6 +1799,9 @@
    ProjFalseEastingGeoKey: 4321000.000000 m
    ProjFalseNorthingGeoKey: 3210000.000000 m
 GCS: 4258/ETRS89
+Datum: 6258/European Terrestrial Reference System 1989
+Ellipsoid: 7019/GRS 1980 (6378137.00,6356752.31)
+Prime Meridian: 8901/Greenwich (0.000000/  0d 0' 0.00"E)
 Projection Linear Units: 9001/metre (1.000000m)

 Corner Coordinates:

PROBLEMS HAVE OCCURRED
test file testlistgeo_out saved
```

**Comment by rouault** [comment] 2021-03-26 20:26
Duplicate of https://github.com/OSGeo/libgeotiff/issues/54

**Closed by rouault** 2021-03-26 20:26 UTC

**Comment by kloczek** [comment] 2021-03-26 20:35
Yep 622a4b2a fixed the issue.
Thx :)
